version: "3.1"

services:
  lotto-web:
    container_name: lotto-web
    image: ${MY_REPOSITORY_URL}/lotto-web:latest
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - CONTEXT_PATH=/lotto
      - DATABASE_URL=jdbc:h2:mem:lotto
      - DATABASE_USERNAME=sa
      - DATABASE_PASSWORD=
      - DATABASE_PLATFORM=H2Dialect
      - DATASOURCE_MAX_POOL_SIZE=10
      - LOGGING_ROOT_LEVEL=warn
      - LOGGING_APP_LEVEL=info
      - ENABLE_API_DOCS=true
      - ENCRYPT_KEY_FILE=/etc/lotto-web/enc.key
    volumes:
      - ~/workspace/docker/share/lotto-web/test.key:/etc/lotto-web/enc.key